//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MTech.Entities.HelperClasses
{
	/// <summary>Field Creation Class for entity TodoItemEntity</summary>
	public partial class TodoItemFields
	{
		/// <summary>Creates a new TodoItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TodoItemFieldIndex.Id); }}
		/// <summary>Creates a new TodoItemEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TodoItemFieldIndex.Title); }}
	}
	

}