//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using MTech.Entities.FactoryClasses;
using MTech.Entities.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MTech.Entities.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitTodoItemEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits TodoItemEntity's info objects</summary>
		private void InitTodoItemEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TodoItemFieldIndex), "TodoItemEntity");
			this.AddElementFieldInfo("TodoItemEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)TodoItemFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("TodoItemEntity", "Title", typeof(System.String), false, false, false, false,  (int)TodoItemFieldIndex.Title, 128, 0, 0);
		}
	}
}