// <auto-generated />
using EFSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFSample.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DomainLayer.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("DomainLayer.Cow", b =>
                {
                    b.HasBaseType("DomainLayer.Animal");

                    b.ToTable("Cow");
                });

            modelBuilder.Entity("DomainLayer.Dog", b =>
                {
                    b.HasBaseType("DomainLayer.Animal");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("DomainLayer.Cow", b =>
                {
                    b.HasOne("DomainLayer.Animal", null)
                        .WithOne()
                        .HasForeignKey("DomainLayer.Cow", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Dog", b =>
                {
                    b.HasOne("DomainLayer.Animal", null)
                        .WithOne()
                        .HasForeignKey("DomainLayer.Dog", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
