//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using MTech.Entities.HelperClasses;
using MTech.Entities.FactoryClasses;
using MTech.Entities.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MTech.Entities.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'TodoItem'.<br/><br/></summary>
	[Serializable]
	public partial class TodoItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static TodoItemEntityStaticMetaData _staticMetaData = new TodoItemEntityStaticMetaData();
		private static TodoItemRelations _relationsFactory = new TodoItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class TodoItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public TodoItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("TodoItemEntity", InheritanceHierarchyType.None, false, (int)MTech.Entities.EntityType.TodoItemEntity, typeof(TodoItemEntity), typeof(TodoItemEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static TodoItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public TodoItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public TodoItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this TodoItemEntity</param>
		public TodoItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for TodoItem which data should be fetched into this TodoItem object</param>
		public TodoItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for TodoItem which data should be fetched into this TodoItem object</param>
		/// <param name="validator">The custom validator object for this TodoItemEntity</param>
		public TodoItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected TodoItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this TodoItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static TodoItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity TodoItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TodoItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)TodoItemFieldIndex.Id, true); }
			set { SetValue((int)TodoItemFieldIndex.Id, value); }		}

		/// <summary>The Title property of the Entity TodoItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TodoItem"."Title".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 128.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Title
		{
			get { return (System.String)GetValue((int)TodoItemFieldIndex.Title, true); }
			set	{ SetValue((int)TodoItemFieldIndex.Title, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace MTech.Entities
{
	public enum TodoItemFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Title. </summary>
		Title,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace MTech.Entities.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: TodoItem. </summary>
	public partial class TodoItemRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticTodoItemRelations
	{

		/// <summary>CTor</summary>
		static StaticTodoItemRelations() { }
	}
}
