//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MTech.Entities.HelperClasses
{
	/// <summary>Field Creation Class for entity AnimalEntity</summary>
	public partial class AnimalFields
	{
		/// <summary>Creates a new AnimalEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AnimalFieldIndex.Id); }}
		/// <summary>Creates a new AnimalEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AnimalFieldIndex.Name); }}
		/// <summary>Creates a new AnimalEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AnimalFieldIndex.Type); }}
	}

	/// <summary>Field Creation Class for entity CowEntity</summary>
	public partial class CowFields
	{
		/// <summary>Creates a new CowEntity.Id field instance</summary>
		public static EntityField2 Id_Animal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CowFieldIndex.Id_Animal); }}
		/// <summary>Creates a new CowEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CowFieldIndex.Name); }}
		/// <summary>Creates a new CowEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CowFieldIndex.Type); }}
		/// <summary>Creates a new CowEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CowFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity DogEntity</summary>
	public partial class DogFields
	{
		/// <summary>Creates a new DogEntity.Id field instance</summary>
		public static EntityField2 Id_Animal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DogFieldIndex.Id_Animal); }}
		/// <summary>Creates a new DogEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DogFieldIndex.Name); }}
		/// <summary>Creates a new DogEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DogFieldIndex.Type); }}
		/// <summary>Creates a new DogEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DogFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity TodoItemEntity</summary>
	public partial class TodoItemFields
	{
		/// <summary>Creates a new TodoItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TodoItemFieldIndex.Id); }}
		/// <summary>Creates a new TodoItemEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TodoItemFieldIndex.Title); }}
	}
	

}