//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using MTech.LLBLGen.Entities.EntityClasses;
using MTech.LLBLGen.Entities.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace MTech.LLBLGen.Entities.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the Animal entity</summary>
		public EntityQuery<AnimalEntity> Animal { get { return Create<AnimalEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Cow entity</summary>
		public EntityQuery<CowEntity> Cow { get { return Create<CowEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Dog entity</summary>
		public EntityQuery<DogEntity> Dog { get { return Create<DogEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the TodoItem entity</summary>
		public EntityQuery<TodoItemEntity> TodoItem { get { return Create<TodoItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the WeatherForecast entity</summary>
		public EntityQuery<WeatherForecastEntity> WeatherForecast { get { return Create<WeatherForecastEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}